### ISSUE TITLE
Pre Pilot checklist

### ISSUE THREAD

**Issue by kushinm** [SchlossVRL/color_scales_affect#1]
- [x] Update script to work with images instead of colored HTML divs @kushinm 
- [x] Add raw consent text as a `.txt` file @annachinni 
- [x] Link with OSF using DataPipe @kushinm @braunh1 @annachinni 
- [x] Add subject Id field to output data
- [x] Add training trials
- [x] Add additional instructions explaining practice trials @braunh1 
- [x] Update instructions and debriefing scripts @braunh1 
- [x] Sort out SONA posting @braunh1 @kushinm 
- [x] Write short R script to plot association data @braunh1 
- [x] PCA plot @kushinm @braunh1
